"""En este archivo se debe escribir la soluci贸n al problema planteado."""

from exceptions import AssocError, CheckError
from functions import assoc


def control(ext, prog):
    """Funci贸n de control de exepciones."""
    try:
        result = assoc(ext, prog)
        if result < 5:
            return result
        else:
            raise AssocError(f"Error de asociaci贸n {result}")

    except CheckError as e:
        return f"Se ha producido la excepci贸n CheckError con el mensaje: '{e}'"
